---

- hosts: all 
  become: true
  roles:
    - sysdev.docker
  tasks:
    - name: Create a data container
      docker_container:
        name: mydata
        image: busybox
        volumes:
          - /data 
